swagger: '2.0'
info:
  version: '1.0'
  title: heroku_store_api
  contact: {}
host: store-api-temzycode.herokuapp.com
basePath: /api/v1/products
securityDefinitions: {}
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /static:
    get:
      summary: Get all product - testing
      tags:
      - Misc
      operationId: Getallproduct-testing
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
  /:
    get:
      summary: Get all product
      tags:
      - Misc
      operationId: Getallproduct
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
    post:
      summary: Create Product
      tags:
      - Misc
      operationId: CreateProduct
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CreateProductRequest'
      responses:
        '200':
          description: ''
          headers: {}
definitions:
  CreateProductRequest:
    title: CreateProductRequest
    example:
      name: my name is Loveth
      price: 28
      featured: true
      company: paystack
    type: object
    properties:
      name:
        type: string
      price:
        type: integer
        format: int32
      featured:
        type: boolean
      company:
        type: string
    required:
    - name
    - price
    - featured
    - company
tags:
- name: Misc
  description: ''